// Generated by CoffeeScript 1.4.0
(function() {
  var AppConfig;

  AppConfig = {
    Stemcell: {
      ViewExtend: 'vendor/Stemcell.View.Extend',
      ModelExtend: 'vendor/Stemcell.Model.Extend',
      DomExtend: 'vendor/Stemcell.Dom.Extend',
      SyncExtend: 'vendor/Stemcell.Sync.Extend'
    }
  };

}).call(this);
