// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define([], function() {
    var AppRouter, router;
    router = {};
    this.router = window.router = new AppRouter();
    Stemcell.history.start();
    Stemcell.setEmulateJSON(true);
    return AppRouter = (function(_super) {

      __extends(AppRouter, _super);

      function AppRouter() {
        return AppRouter.__super__.constructor.apply(this, arguments);
      }

      AppRouter.prototype.initialize = function() {
        return this.setMessengers({});
      };

      AppRouter.prototype.routes = {
        '': ''
      };

      return AppRouter;

    })(Stemcell.Router);
  });

}).call(this);
